### ISSUE TITLE
초기 시범용 인프라 및 구조 작업

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/SeeYouAgain_iOS#1]
## 💡 요약
- 프로젝트 인프라 및 구조 설계 작업

## ✅ 체크포인트
- 프로젝트 인프라 작업
- 프로젝트 구조 설계
- 초기 설정 등 작업

## 💻 Task
- [x] 전체 구조 및 로직 설계
- [x] fastlane을 통한 CI/CD 작업
- [x] Tuist를 통한 모듈화 및 에셋/프로젝트 관리 작업
- [x] grunt Shell script를 통한 작업 환경 설정 및 자동화 작업
  - [x] 프로젝트 생성 및 관리
  - [x] PR 자동화
  - [x] 배포 자동화
- [x] TCACoordinator 시범용 코드 구현
- [x] DS 및 컬러/아이콘/폰트/이미지 에셋 템플릿화 작업 및 코드에서 시범 구현
- [x] App Store Connect에 앱 생성 및 기타 초기 작업
