### ISSUE TITLE
grunt 배포 테스트

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/SeeYouAgain_iOS#10]
## 💡 요약
- grunt deploy-local 배포 테스트

## ✅ 체크포인트
- grunt를 이용한 배포 테스트 및 보완

## 💻 Task
- [x] grunt 배포 테스트
- [x] grunt deploy-local 필요 부분 보완
- [x] ipa / dSYM 파일 저장 경로 변경
