### ISSUE TITLE
핫 키워드 간헐적으로 애니메이션 동작하지 않는 현상 

### ISSUE THREAD

**Issue by lina0322** [mash-up-kr/SeeYouAgain_iOS#169]
## 💡 요약

- 간헐적으로 핫 키워드 원이 애니메이션 동작하지 않아서, 화면에 핫키워드 노출 안됨

## ✅ 체크포인트

- 처음 시작시
- 리프레시
- 처음 시작 후 다른 탭에서 동작 한 뒤 왔을 때 (여기가 가장 심함)
- 리프레시 후 다른 탭에서 동작 한 뒤 왔을 때
- 핫 키워드 화면에서 백그라운드 -> 포그라운드
- 핫 키워드 외 화면에서  백그라운드 -> 포그라운드
- 핫 키워드 외 화면에서  백그라운드 -> 포그라운드 후 다른 화면에서 동작 후 핫키워드

## 💻 Task

- [x] 처음 시작시
- [x] 리프레시
- [x] 처음 시작 후 다른 탭에서 동작 한 뒤 왔을 때 (여기가 가장 심함)
- [x] 리프레시 후 다른 탭에서 동작 한 뒤 왔을 때
- [x] 핫 키워드 화면에서 백그라운드 -> 포그라운드
- [x] 핫 키워드 외 화면에서  백그라운드 -> 포그라운드
- [x] 핫 키워드 외 화면에서  백그라운드 -> 포그라운드 후 다른 화면에서 동작 후 핫키워드
