### ISSUE TITLE
watchOS 구현

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/SeeYouAgain_iOS#181]
## 💡 요약
- wathOS 구현 

## ✅ 체크포인트
- 피그마에 완료된 디자인에 따른 watchOS 구현

## 💻 Task
- [ ] 홈 화면 구현
- [ ] 핫키워드 화면 구현
- [ ] 키워드 화면 구현
- [ ] 숏스 저장 API 연동
- [ ] 폰에서 보기 기능 연동

**Comment by klmyoungyun** [comment]
✅ 7.25(화) 
- `tuist로 타겟 추가` 체크포인트 추가
