### ISSUE TITLE
카테고리 통계 수정

### ISSUE THREAD

**Issue by AhnSangHee** [mash-up-kr/SeeYouAgain_iOS#216]
## 💡 요약

카테고리 통계 수정

## ✅ 체크포인트

- 가장 많이 읽은 카테고리를 카테고리 통계 아이콘으로 표시
- 모든 읽은 카테고리 정보 받아오고 있어서 TOP 3만 저장하도록 수정 필요

## 💻 Task

- [x] 가장 많이 읽은 카테고리를 카테고리 통계 아이콘으로 표시
- [x] 카테고리 TOP 3만 저장하도록 수정
- [ ] 카테고리 그래프 보이지 않는 이슈 수정
