### ISSUE TITLE
카테고리 선택 API 구현 및 연동 & 카테고리 설정 화면 마무리

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/SeeYouAgain_iOS#51]
## 💡 요약
- 카테고리 선택 API 구현 및 연동

## ✅ 체크포인트
- 서버 카테고리 선택 API 수정 후 반영 예정

## 💻 Task
- [x] 카테고리 선택 Request / Response DTO 구현
- [x] 카테고리 선택 API 구현
- [x] SetCategoryCore에 연동
- [x] 카테고리 설정화면 디자인에 맞춰 마무리
