### ISSUE TITLE
키워드 내 뉴스 리스트, 숏스 추가 완료 화면

### ISSUE THREAD

**Issue by AhnSangHee** [mash-up-kr/SeeYouAgain_iOS#54]
## 💡 요약

키워드 내 뉴스 리스트, 숏스 추가 완료 화면

## ✅ 체크포인트

- 키워드 내 뉴스 리스트, 숏스 추가 완료 화면

## 💻 Task

- [x] 키워드 내 뉴스 리스트 화면 구현
- [x] 키워드 내 뉴스 클릭하면 웹뷰 이동하도록 구현
- [x] 카테고리 뱃지 타입 (CategoryView) 구현
- [x] 숏스 추가 완료 화면 구현
