### ISSUE TITLE
디자인 디테일 수정

### ISSUE THREAD

**Issue by AhnSangHee** [mash-up-kr/SeeYouAgain_iOS#59]
## 💡 요약

디자인 변경사항 및 디테일을 수정합니다.

## ✅ 체크포인트

- 디자인 디테일 수정

## 💻 Task

- [x] 오늘의숏스, 오래 간직할 숏스 포함하는 뷰랑 바깥 뷰 사이의 패딩이 기기마다 달라지는 이슈 수정
- [x] 이번 달 ~숏스 중을 포함하는 뷰 배경 블러 처리
- [x] 이번 달 ~숏스 중에 해당하는 뷰 테두리 색상 변경
