### ISSUE TITLE
앱 아이콘 설정 및 런치스크린 / 스플래쉬 내 로고 추가

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/SeeYouAgain_iOS#65]
## 💡 요약
- 앱 아이콘 설정 및 런치스크린 / 스플래쉬 내 로고 추가

## ✅ 체크포인트
- 앱 아이콘 추가 (Prod / Dev)
- 런치스크린 / 스플래쉬 내 로고 추가

## 💻 Task
- [x] 앱 아이콘 추가 및 확인
- [x] 런치스크린 로고 및 배경 추가
- [x] 스플래쉬 로고 추가
