### ISSUE TITLE
앱 스토어 내 정보 및 썸네일 이미지 등록

### ISSUE THREAD

**Issue by GREENOVER** [mash-up-kr/SeeYouAgain_iOS#66]
## 💡 요약
- 앱 스토어 커넥트 사이트 내 숏스 앱에 대해 정보 및 썸네일 이미지 등록

## ✅ 체크포인트
- 앱 아이콘
- 대표 썸네일 이미지
- 기타 정보
  - 앱 카테고리
  - 앱 타이틀 및 서브타이틀
- 테스트 플라이트 내 또보겠지 인원 초대

## 💻 Task
- [x] 앱 아이콘 추가
- [x] 대표 썸네일 이미지 추가
- [x] 기타 정보 추가
- [x] 테플 인원 초대
