### ISSUE TITLE
오래 간직할 숏스 화면 구현

### ISSUE THREAD

**Issue by AhnSangHee** [mash-up-kr/SeeYouAgain_iOS#69]
## 💡 요약

오래 간직할 숏스 화면 구현

## ✅ 체크포인트

- 오래 간직할 숏스 화면 구현

## 💻 Task

- [x] 오래 간직할 숏스 화면 구현하기
- [x] 뉴스 카드 클릭 시 웹 이동
- [x] 편집모드에 따라 카드 삭제 가능
