### ISSUE TITLE
핫 키워드 페이지 구현

### ISSUE THREAD

**Issue by lina0322** [mash-up-kr/SeeYouAgain_iOS#76]
## 💡 요약

핫 키워드 페이지 구현

## ✅ 체크포인트

- 
## 💻 Task

- [x] 타이틀
- [ ] bubbleView UI 구현
  - [ ] 써클 UI 구현
    - [ ] 블러
  - [x] 써클 애니메이션 구현
- [x] pullToRefresh
- [x] hot 탭 클릭시 동작 구현
- [x] 키워드 버튼 눌렀을때 동작 구현
