### ISSUE TITLE
마이 페이지 > 오늘의 숏스 API 연동 외..

### ISSUE THREAD

**Issue by AhnSangHee** [mash-up-kr/SeeYouAgain_iOS#82]
## 💡 요약

마이 페이지 > 오늘의 숏스 API 연동

## ✅ 체크포인트

- 마이 페이지 > 오늘의 숏스 API 연동
- 뉴스 리스트랑 엮인 화면 잘 체크하기..

## 💻 Task

- [x] 오늘의 숏스 조회 API 연동
- [x] 오늘의 숏스 삭제 API 연동
- [x] 숏스 내 뉴스 조회 API 연동
   - [x] 오늘의 숏스 카드 클릭 시 뉴스 리스트 화면으로 이동
   - [x] 메인 카드 클릭 시 뉴스 리스트 화면으로 이동 
- [x] 오늘의 숏스 다 읽었어요 API 연동
- [x] 뉴스 카테고리에 따라 뱃지 색상 다르게 구현
- [x] 숏스 카테고리에 따른 카드 이미지 표시
- [x] 핫 키워드로 숏스 조회 API 연동
